version: "3.7"
services:
  db:
    image: "postgres:15.3"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "account"
  service:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile-app
    ports:
      - "8080:8080"