version: "3.7"
services:
  db:
    image: "postgres:15.3"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "account"
    ports:
      - "5432:5432"
#  rabbitmq:
#    image: "rabbitmq:3-management"
#    ports:
#      - "5672:5672"
#      - "15672:15672"
