version: "3.7"
services:
  db:
    image: "postgres:15.3"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "account"
#    ports:
#      - "5432:5432"
  service:
    image: "account:1.0.0"
    ports:
      - "8080:8080"